<?php
/**
 * @var \DMTQ\GoogleTagManager\Block\Gtm $block
 * @var \Magento\Framework\Escaper $escaper
 */
// phpcs:disable
?>
<?php $dataLayer = $block->getDataLayer(); ?>
<?php if ($block->isDataLayerEnabled()): ?>
<script>
    window.dataLayer = window.dataLayer || [];
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "DMTQ_GoogleTagManager/js/datalayer": {
                "isUserDataEnabled": <?= $block->isUserDataEnabled() ? 'true' : 'false'; ?>,
                "data": <?= $dataLayer ? $dataLayer->getJson() : '{}'; ?>
            }
        }
    }
</script>
<?php endif; ?>
<?php if (!empty($block->getContainerId())): ?>
<?= $block->getChildHtml('dmtq.gtm.default'); ?>
<?php endif; ?>
